# SPDX-FileCopyrightText: Copyright (c) Pierre-Yves Lapersonne
# SPDX-License-Identifier: MIT
# ‚úø‚úø‚úø‚úø  ï ‚Ä¢·¥•‚Ä¢ î/ Ô∏ª„Éá‚ïê‰∏Ä

# https://github.com/soulteary/github-profile-trophy-action/

name: Update README Trophies
on:
  schedule:
    - cron: 0 7 1 * * # Each #st day of the month at 07:00
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Generate trophy card
        uses: soulteary/github-profile-trophy-action@deb1c20e108c1815a7ba24b3e86a8e9ffe1b568e # (v1.0.0)
        with:
          options: 'username=${{ github.repository_owner }}&theme=radical&no-frame=false&no-bg=true&margin-w=4'
          path: .github/assets/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Commit trophy card
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/assets/trophy.svg
          git commit -m $'chore(ü§ñ): update README trophies\n\nThis is an automated commit' || exit 0
          git push